[package]
name = "proxies"
version = "0.1.0"
authors = ["Antigravity"]
edition = "2024"
publish = false

[dependencies.multiversx-sc]
version = "0.64.1"

[dependencies.common]
path = "../common"

[dependencies.escrow]
path = "../escrow"
