[package]
name = "escrow-meta"
version = "0.1.0"
authors = ["Antigravity"]
edition = "2024"
publish = false

[dependencies.escrow]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.1"
